# Generated by Django 4.1 on 2022-09-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('count_of_puffs', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SinglePodImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='mediafiles/single-pods/')),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('single_pod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tastes', to='app.singlepod')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='app.taste')),
            ],
        ),
        migrations.AddField(
            model_name='singlepod',
            name='images',
            field=models.ManyToManyField(to='app.singlepodimages'),
        ),
        migrations.AddField(
            model_name='singlepod',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.manufacturer'),
        ),
    ]
