# Generated by Django 4.1 on 2022-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_singlepod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepod',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
