# Generated by Django 4.1.1 on 2022-09-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_singlepod_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='mediafiles/liquid/')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerLiquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLiquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Принят', 'Принят'), ('Достовляется', 'Достовляется'), ('Доставлен', 'Доставлен')], default='В обработке', max_length=125)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquid_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('liquid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquid_tastes', to='app.liquid')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquid_stocks', to='app.liquidtaste')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquid_order_details', to='app.orderliquid')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquid_orders', to='app.liquidtaste')),
            ],
        ),
        migrations.AddField(
            model_name='liquid',
            name='images',
            field=models.ManyToManyField(to='app.liquidimages'),
        ),
        migrations.AddField(
            model_name='liquid',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.manufacturerliquid'),
        ),
    ]
